apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tfps75psk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tfps75psk-go 
  name: tfps75psk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tfps75psk-go 
